force-app/main/default/objects/Approval_Record__c/Approval_Record__c.object-meta.xml
<CustomObject>
    <label>Approval Record</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aproval Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval_Record__c/fields/Approval_Name__c.field-meta.xml
<CustomField>
    <fullName>Approval_Name__c</fullName>
    <label>Approval Name</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Approval_Record__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_Record__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>T1</fullName>
            </value>
            <value>
                <fullName>T2</fullName>
            </value>
            <value>
                <fullName>T3</fullName>
            </value>
            <value>
                <fullName>T4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApprovalHandeller.cls
public class ApprovalHandeller {
    public static void papulateName(list<Approval_Record__c> appList){
        for(Approval_Record__c a : appList){
        a.Name = a.Product_Name__c+'-'+a.Quantity__c+'-'+a.Type__c;
        }
    }
    
   /* public static void duplicateFind(list<Approval_Record__c> appLis){
    
    set<string> newNameSet = new set<string>();
    set<string> dbNameSet = new set<string>();


    for(Approval_Record__c a : appLis){

        newNameSet.add(a.Approval_Name__c);
    }

    for(Approval_Record__c aq : [select id, Approval_Name__c from Approval_Record__c where Approval_Name__c IN: newNameSet]){

        dbNameSet.add(aq.Approval_Name__c);

    }

    for(Approval_Record__c an : appLis){

        if(dbNameSet.contains(an.Approval_Name__c))

            an.addError('You are inserting Duplicate approval record');

    }


    }*/
}