force-app/main/default/objects/Account/fields/Both_of_Salary__c.field-meta.xml
<CustomField>
    <fullName>Both_of_Salary__c</fullName>
    <label>Both of Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Develper_Salary__c.field-meta.xml
<CustomField>
    <fullName>Develper_Salary__c</fullName>
    <label>Develper Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Manager_Salary__c.field-meta.xml
<CustomField>
    <fullName>Manager_Salary__c</fullName>
    <label>Manager Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Salaray__c.field-meta.xml
<CustomField>
    <fullName>Salaray__c</fullName>
    <label>Salaray</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SalaryUpdateHandller.cls
public class SalaryUpdateHandller {
    public static void updateSalaryOnAcc(List<Contact> con){
        try{
            list<Account> accListToUpdate = new list<Account>();
            Set<Id> setOfId = new Set<Id>();
              for(Contact cn : con){
                 setOfId.add(cn.accountid);  
              }
            if(setOfId != null && setOfId.size() > 0){
                Account acc = new Account();
                Decimal devSal = 0.0;
                Decimal mangSal = 0.0;
                Account queryAcc = [select id,Develper_Salary__c,Manager_Salary__c,Both_of_Salary__c,(select id,Type__c,Salaray__c from Contacts) from Account where id IN : setOfId LIMIT 1];
                for(Contact cnn : queryAcc.Contacts){
                    if(cnn.Type__c  == 'Developer'){
                        devSal += cnn.Salaray__c;
                    }
                    System.debug('devSal::'+devSal);
                    if(cnn.Type__c  == 'Manager'){
                        mangSal += cnn.Salaray__c;
                     System.debug('mangSal::'+mangSal);   
                    }
                    queryAcc.Develper_Salary__c = devSal;
                    System.debug('queryAcc.Develper_Salary__c::'+queryAcc.Develper_Salary__c);
                    queryAcc.Manager_Salary__c = mangSal;
                    System.debug('queryAcc.Manager_Salary__c::'+queryAcc.Manager_Salary__c);
                    queryAcc.Both_of_Salary__c = devSal + mangSal;
                    //acc.Id = queryAcc.Id;
                    //accListToUpdate.add(queryAcc);
                }
                    Update queryAcc;
            }
        }
        catch(exception e) 
        {
            system.debug('Exception message:-'+e.getMessage() +'  LineNumber:-'+e.getLineNumber() +'  StackTraceString:-'+e.getStackTraceString());           
        }
    }
}