force-app/main/default/objects/Account/fields/Maximum_Amount__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Amount__c</fullName>
    <label>Maximum Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Minumun_Amount__c.field-meta.xml
<CustomField>
    <fullName>Minumun_Amount__c</fullName>
    <label>Minumun Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Its a custom object</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice</relationshipLabel>
    <relationshipName>Invoice</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>How much</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of invoice</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InvoiceHandeler.cls
public class InvoiceHandeler {
    
    public static void rollupSummery(){
        
        List<Account> accountList = new List<Account>();
        List<AggregateResult> rollup = [select sum(Amount__c)totalAmount,max(Amount__c)maxAmount,min(Amount__c)minAmount,Account__c from Invoice__c group By Account__c];
        for(AggregateResult agg : rollup)
        {
            if(agg.get('Account__c') != null)
            {
            Account acc = new Account();
            acc.Id = (Id)agg.get('Account__c');
            acc.Total_Amount__c = (Decimal)agg.get('totalAmount');
            acc.Maximum_Amount__c = (Decimal)agg.get('maxAmount');
            acc.Minumun_Amount__c = (Decimal)agg.get('minAmount');
            accountList.add(acc);
            }
        }
        
        if(!accountList.isEmpty()){
            update accountList;
        }   
    }
    
    public static void oneActive(List<Invoice__c > allInvoiceList){
        Set<Id> acc = new Set<Id>();
        //List<Invoice__c> invoiceList = new List<Invoice__c>([ select id,Status__c from  Invoice__C where Status__C = 'Open'and Account__c=:acc]);
        
        for(Invoice__c i : allInvoiceList){
            acc.add(i.Account__c);
        } 
        
        List<Invoice__c> invoiceList = new List<Invoice__c>([ select id,Status__c from  Invoice__C where Status__C = 'Open'and Account__c=:acc]);
        
        for(Invoice__c i : allInvoiceList){
            
            if(i.Status__c =='Open'){
                if(invoiceList.size()>1){
                    i.adderror('only one application can active');
                }
            } 
        }
        
    }
}