force-app/main/default/objects/Distributor__c/Distributor__c.object-meta.xml
<CustomObject>
    <label>Distributor</label>
    <nameField>
        <label>Distributor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distributors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Distributor__c/fields/Accounts_Count__c.field-meta.xml
<CustomField>
    <fullName>Accounts_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Accounts Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Distributor_List__c/Distributor_List__c.object-meta.xml
<CustomObject>
    <label>Distributor List</label>
    <nameField>
        <label>Distributor List	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distributor Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Distributor_List__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <label>Distributor</label>
    <referenceTo>Distributor__c</referenceTo>
    <relationshipLabel>Distributor Lists</relationshipLabel>
    <relationshipName>Distributor_Lists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Distributor_List__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Distributor Lists</relationshipLabel>
    <relationshipName>Distributor_Lists</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NoOfUniqueAccountsonDistributor.cls
public class NoOfUniqueAccountsonDistributor{
    Public static void updateStrategy(List<Id> dstrlistID){
        List<Distributor__c> dstrlistUpdate = new List<Distributor__c>();
        Set<Id> uniqueAccountIDs = new Set<Id>();
        List<Distributor__c> dstrlist = [SELECT Id,name,(SELECT Id,Opportunity__c,Opportunity__r.AccountID FROM 
                                         Distributor_Lists__r where Distributor__c IN :dstrlistID)
                                         FROM Distributor__c WHERE ID IN :dstrlistID];
        for(Distributor__c dtr : dstrlist)
        {
            for(Distributor_List__c dls : dtr.Distributor_Lists__r){
              
                uniqueAccountIDs.add(dls.Opportunity__r.AccountID);
            }
            dtr.Accounts_Count__c = uniqueAccountIDs.size();
            dstrlistUpdate.add(dtr);
        }
        System.debug('uniqueAccountIDs' +uniqueAccountIDs.size());
        
        update dstrlistUpdate;
    }
}